### PR TITLE
Remove liquid extension append on all stylesheets

### PR DESCRIPTION
**Pull request by t-kelly**
### What are you trying to accomplish with this PR?

Fixes https://github.com/Shopify/slate-tools/issues/57

### Checklist
For contributors:
- [x] I have [updated the docs](https://github.com/Shopify/slate/blob/master/CONTRIBUTING.md#documentation) to reflect these changes, if applicable.

For maintainers:
- [ ] I have :tophat:'d these changes.
- [ ] I have bumped the `package.json` version in a separate PR, if applicable.

### CODE REVIEW

**Comment by macdonaldr93** [comment]
Just read up on the issue and I'm not sure this means that we should completely remove this possibility for other partners. Wouldn't this be a pretty breaking change?

Another side note, I'm pretty sure the only reason we use `css-import` is because it doesn't break with `.liquid`. If this goes through, we could probably use `node-sass` and `autoprefixer` with our css tooling now.

**Comment by NathanPJF** [comment]
> I'm not sure this means that we should completely remove this possibility for other partners.

What possibility are you referring to @macdonaldr93 ?

> Wouldn't this be a pretty breaking change?

You're right.  Had a quick chat with @t-kelly and while we feel this is a step in the right direction, we don't want to implement a breaking change just yet.  Better to bundle it with other break changes in a future release since it's not high priority.  So this PR will just sit here for the time being.

> If this goes through, we could probably use `node-sass` and `autoprefixer` with our css tooling now.

Thought about this, but makes me uneasy.  We could compile Sass with the latest version, but I feel this messes with expectations.  If I decide in the future I need to add one Liquid variable to my `scss` file, I would need to go through the entire file to make sure it's Sass 3.2 compatible.  That's a lot of work, so I'd rather have Shopify do all the compiling.  If people want to compile their Sass in the local environment, custom hooks would be the way to do it.

**Comment by macdonaldr93** [comment]
For that first part, I was referring to the fact that partner's wouldn't be able to use liquid in the `scss` anymore. But maybe that's not the case?

**Comment by NathanPJF** [comment]
> For that first part, I was referring to the fact that partner's wouldn't be able to use liquid in the scss anymore. But maybe that's not the case?

That's what was happening in this branch - but that wasn't the end goal.  You can see a better description of the end goal in #57:

> Potential idea: Remove `.pipe(extReplace('.scss.liquid', '.scss'))` from the function. If developers need Shopify to compile SCSS with Liquid, then they will have to write `*.liquid` on the end of the file name.

### What that would look like

```
src/
-- global/
-- modules/
-- settings/
-- themes.scss.liquid
-- framework.scss
```
To become:
```
dist/
-- themes.scss.liquid
-- framework.scss
```

Or even, do the Sass compilation for you (which I keep going back and forth on)
```
dist/
-- themes.scss.liquid
-- framework.css
```

However, we'd need more work on this branch to get that done.  Because by having `theme.scss.liquid` in the `src/` directory makes that file get skipped over by `processCss()`.

**Pull request closed without merging**
