### PR TITLE
Upgrade browser-sync to 2.18.12

### PR DESCRIPTION
**Pull request by alistairholt**
Fixes 'Disconnected from BrowserSync' message in the browser.

### Checklist
For contributors:
- [ ] I have [updated the docs](https://github.com/Shopify/slate/blob/master/CONTRIBUTING.md#documentation) to reflect these changes, if applicable.

For maintainers:
- [ ] I have :tophat:'d these changes.
- [ ] I have bumped the `package.json` version in a separate PR, if applicable.

### CODE REVIEW

**Comment by NathanPJF** [comment]
@alistairholt Could you please provide some more information on the issue this is resolving?  What's the issue with the message you're seeing?

**Comment by alistairholt** [comment]
@NathanPJF I'm actually still having this issue since I switched to 2.18.12 locally although I think it relieved it slightly. When I'm running `slate watch` and have http://localhost:3000 open in my browser to view the proxied version of the Shopify store I'm working on I often get a 'Disconnected from BrowserSync' message popping up in the top right of the page. I had read that this was an issue with browsersync that had been fixed since v2.18.2 but I'm not sure this is actually the case.

**Comment by NathanPJF** [comment]
> I had read that this was an issue with browsersync that had been fixed since v2.18.2

When I was looking around for context I did see that people were saying that on other projects that "Disconnected" message was never fading out after being displayed.  So the problem was the modal was permanently covering their headers.  I tried reproducing last night, but didn't have any issue of it not going away.

What you're describing sounds a bit different:

> I often get a 'Disconnected from BrowserSync' message popping up in the top right of the page.

Is the message accurate, though?  Are you randomly getting disconnected, or is it saying you're disconnected but really you're still able to update and get live reload?

Mind putting some more information about your setup? Node version, NPM version, operating system, version of slate-cli and slate-tools.

**Comment by t-kelly** [comment]
This repo has been deprecated. Please reopen rhis PR in the [`Shopify/slate`](https://github.com/Shopify/slate) repo.

**Pull request closed without merging**
